type DiscoverTracksMessage = {
  type: 'DISCOVER_CAPTION_TRACKS';
  tabId: number;
  language: string;
  videoId: string;
};

type FetchCaptionResourceMessage = {
  type: 'FETCH_CAPTION_RESOURCE_MAIN_WORLD';
  tabId: number;
  captionUrl: string;
};

type FetchCaptionResourceMainWorldResult = {
  ok: boolean;
  status: number;
  contentType: string;
  text: string;
};

async function fetchCaptionResourceMainWorld(captionUrl: string): Promise<FetchCaptionResourceMainWorldResult> {
  const response = await fetch(captionUrl, {
    credentials: 'include'
  });

  const text = await response.text();

  return {
    ok: response.ok,
    status: response.status,
    contentType: response.headers.get('content-type') ?? 'unknown',
    text
  };
}

// YouTube now requires a proof-of-origin token ("pot") plus a matching set of
// client-identity params on caption requests; the static baseUrl embedded in
// ytInitialPlayerResponse never carries them, so a plain fetch of it comes
// back HTTP 200 with an empty body. The token is generated by an obfuscated
// attestation script and isn't exposed anywhere a content script can read it
// passively (checked window.ytcfg/yt/ytplayer, IndexedDB, localStorage,
// sessionStorage, cookies - nothing). Instead, we nudge the page's own player
// into making one real caption request (by toggling its native CC button)
// and observe the resulting URL via chrome.webRequest, then reuse those
// params on our own request.
async function triggerCaptionDisplayMainWorld(): Promise<{ attempted: boolean; forcedRefresh: boolean }> {
  const button = document.querySelector('.ytp-subtitles-button') as HTMLButtonElement | null;
  if (!button) {
    return { attempted: false, forcedRefresh: false };
  }

  const alreadyOn = button.getAttribute('aria-pressed') === 'true';

  if (alreadyOn) {
    // The pot token behind an already-showing caption track can expire
    // between "Load Transcript" clicks. Toggling off then on again forces
    // the player to mint and request a genuinely fresh one instead of
    // silently reusing whatever we last observed.
    button.click();
    await new Promise((resolve) => setTimeout(resolve, 300));
    button.click();
    return { attempted: true, forcedRefresh: true };
  }

  button.click();
  return { attempted: true, forcedRefresh: false };
}

const POT_CLIENT_PARAM_KEYS = ['c', 'cver', 'cplayer', 'cos', 'cosver', 'cplatform', 'cbr', 'cbrver', 'xorb', 'xobt', 'xovt'];

type CapturedPotToken = {
  pot: string;
  potc?: string;
  clientParams: Record<string, string>;
  capturedAt: number;
};

const capturedPotByTab = new Map<number, CapturedPotToken>();

if (chrome.webRequest && typeof chrome.webRequest.onBeforeRequest?.addListener === 'function') {
  chrome.webRequest.onBeforeRequest.addListener(
    (details): undefined => {
      if (typeof details.tabId !== 'number' || details.tabId < 0) {
        return undefined;
      }

      try {
        const url = new URL(details.url);
        const pot = url.searchParams.get('pot');
        if (!pot) {
          return undefined;
        }

        const clientParams: Record<string, string> = {};
        for (const key of POT_CLIENT_PARAM_KEYS) {
          const value = url.searchParams.get(key);
          if (value) {
            clientParams[key] = value;
          }
        }

        capturedPotByTab.set(details.tabId, {
          pot,
          potc: url.searchParams.get('potc') ?? undefined,
          clientParams,
          capturedAt: Date.now()
        });

        console.log('Lamiss POC: native pot token observed = true');
      } catch {
        // malformed URL; nothing to capture
      }

      return undefined;
    },
    { urls: ['*://www.youtube.com/api/timedtext*'] }
  );
}

async function ensureFreshPotToken(tabId: number): Promise<CapturedPotToken | undefined> {
  const requestedAt = Date.now();

  try {
    await chrome.scripting.executeScript({
      target: { tabId },
      world: 'MAIN' as chrome.scripting.ExecutionWorld,
      func: triggerCaptionDisplayMainWorld
    });
  } catch {
    // If we can't toggle captions, fall through and use whatever is cached.
  }

  const deadline = Date.now() + 3000;
  while (Date.now() < deadline) {
    const cached = capturedPotByTab.get(tabId);
    if (cached && cached.capturedAt >= requestedAt) {
      return cached;
    }
    await new Promise((resolve) => setTimeout(resolve, 200));
  }

  return capturedPotByTab.get(tabId);
}

function discoverCaptionTracksMainWorld(expectedVideoId: string): {
  success: boolean;
  error?: string;
  diagnostics?: unknown;
  tracks?: Array<{ languageCode?: string; name?: { simpleText?: string; runs?: Array<{ text?: string }> }; baseUrl?: string; kind?: string }>;
} {
  const globalWindow = window as typeof window & {
    ytInitialPlayerResponse?: {
      videoDetails?: { videoId?: string };
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: CaptionTrack[];
        };
      };
    };
    ytInitialData?: unknown;
    ytInitialPlayerConfig?: unknown;
  };

  // window.ytInitialPlayerResponse is a load-time snapshot: on YouTube's
  // client-side navigation (e.g. clicking a related video) it keeps
  // describing whichever video the page loaded first. The player element's
  // own getPlayerResponse() always reflects whatever video is currently
  // loaded, so prefer it and fall back to the snapshot only if unavailable.
  const moviePlayer = document.getElementById('movie_player') as (Element & { getPlayerResponse?: () => unknown }) | null;
  const livePlayerResponse = typeof moviePlayer?.getPlayerResponse === 'function'
    ? (moviePlayer.getPlayerResponse() as typeof globalWindow.ytInitialPlayerResponse)
    : undefined;

  const playerResponse = livePlayerResponse ?? globalWindow.ytInitialPlayerResponse;
  const playerResponseSource = livePlayerResponse ? 'live' : 'initial-snapshot';
  const playerResponseVideoId = playerResponse?.videoDetails?.videoId;

  if (expectedVideoId && playerResponseVideoId && playerResponseVideoId !== expectedVideoId) {
    return {
      success: false,
      error: 'Player response video ID does not match the requested video yet',
      diagnostics: {
        playerResponseSource,
        playerResponseVideoId,
        expectedVideoId
      }
    };
  }

  const playerResponseKeys = playerResponse ? Object.keys(playerResponse) : [];
  const captions = playerResponse?.captions;
  const captionsKeys = captions ? Object.keys(captions) : [];
  const renderer = captions?.playerCaptionsTracklistRenderer;
  const rendererKeys = renderer ? Object.keys(renderer) : [];
  const tracks = renderer?.captionTracks;
  const ytInitialData = globalWindow.ytInitialData;
  const ytInitialDataKeys = ytInitialData ? Object.keys(ytInitialData as Record<string, unknown>) : [];
  const ytInitialPlayerConfig = globalWindow.ytInitialPlayerConfig;
  const ytInitialPlayerConfigKeys = ytInitialPlayerConfig ? Object.keys(ytInitialPlayerConfig as Record<string, unknown>) : [];

  const diagnostics = {
    playerResponseSource,
    playerResponseVideoId,
    playerResponseExists: Boolean(playerResponse),
    playerResponseType: playerResponse ? typeof playerResponse : 'undefined',
    playerResponseKeys,
    captionsExists: Boolean(captions),
    captionsType: captions ? typeof captions : 'undefined',
    captionsKeys,
    rendererExists: Boolean(renderer),
    rendererKeys,
    captionTracksExists: Boolean(tracks),
    captionTracksIsArray: Array.isArray(tracks),
    captionTracksCount: Array.isArray(tracks) ? tracks.length : 0,
    ytInitialDataExists: Boolean(ytInitialData),
    ytInitialDataKeys,
    ytInitialPlayerConfigExists: Boolean(ytInitialPlayerConfig),
    ytInitialPlayerConfigKeys,
    alternativeCaptionMetadataPath: Boolean(globalWindow.ytInitialData || globalWindow.ytInitialPlayerConfig || globalWindow.ytInitialPlayerResponse)
  };

  if (!tracks || !Array.isArray(tracks)) {
    return {
      success: false,
      error: 'YouTube caption tracks are not available',
      diagnostics
    };
  }

  return {
    success: true,
    tracks: tracks.map(track => ({
      languageCode: track.languageCode,
      name: track.name,
      baseUrl: track.baseUrl,
      kind: track.kind
    })),
    diagnostics
  };
}

function isDiscoverTracksMessage(message: unknown): message is DiscoverTracksMessage {
  if (typeof message !== 'object' || message === null || !('type' in message) || !('tabId' in message) || !('language' in message) || !('videoId' in message)) {
    return false;
  }

  const typed = message as { type?: string; tabId?: unknown; language?: unknown; videoId?: unknown };
  if (typed.type !== 'DISCOVER_CAPTION_TRACKS') {
    return false;
  }

  if (!Number.isInteger(typed.tabId) || typeof typed.tabId !== 'number' || typed.tabId < 0) {
    return false;
  }

  if (typeof typed.videoId !== 'string' || typed.videoId.trim().length === 0) {
    return false;
  }

  return typeof typed.language === 'string' && typed.language.trim().length > 0;
}

function isFetchCaptionResourceMessage(message: unknown): message is FetchCaptionResourceMessage {
  if (typeof message !== 'object' || message === null || !('type' in message) || !('tabId' in message) || !('captionUrl' in message)) {
    return false;
  }

  const typed = message as { type?: string; tabId?: unknown; captionUrl?: unknown };
  if (typed.type !== 'FETCH_CAPTION_RESOURCE_MAIN_WORLD') {
    return false;
  }

  if (!Number.isInteger(typed.tabId) || typeof typed.tabId !== 'number' || typed.tabId < 0) {
    return false;
  }

  return typeof typed.captionUrl === 'string' && typed.captionUrl.trim().length > 0;
}

chrome.runtime.onMessage.addListener((message: unknown, _sender, sendResponse) => {
  if (!isFetchCaptionResourceMessage(message)) {
    return false;
  }

  const tabId = message.tabId;
  const requestedCaptionUrl = message.captionUrl;

  const apiAvailable = Boolean(chrome.scripting && typeof chrome.scripting.executeScript === 'function');
  if (!apiAvailable) {
    sendResponse({
      success: false,
      error: 'chrome.scripting API is unavailable in this context'
    });
    return true;
  }

  (async () => {
    try {
      const potToken = await ensureFreshPotToken(tabId);
      let captionUrl = requestedCaptionUrl;

      if (potToken?.pot) {
        const urlWithPot = new URL(captionUrl);
        urlWithPot.searchParams.set('pot', potToken.pot);
        if (potToken.potc) {
          urlWithPot.searchParams.set('potc', potToken.potc);
        }
        for (const [key, value] of Object.entries(potToken.clientParams)) {
          urlWithPot.searchParams.set(key, value);
        }
        captionUrl = urlWithPot.toString();
        console.log('Lamiss POC: pot token attached to caption request = true');
      } else {
        console.log('Lamiss POC: pot token attached to caption request = false');
      }

      console.log('Lamiss POC: caption fetch executing in MAIN world = true');
      const results = await chrome.scripting.executeScript({
        target: { tabId },
        world: 'MAIN' as chrome.scripting.ExecutionWorld,
        func: fetchCaptionResourceMainWorld,
        args: [captionUrl]
      });

      const result = results[0]?.result as FetchCaptionResourceMainWorldResult | undefined;
      if (!result) {
        sendResponse({
          success: false,
          error: 'Unable to fetch caption resource in MAIN world'
        });
        return;
      }

      console.log('Lamiss POC: MAIN caption HTTP request completed = true');
      console.log('Lamiss POC: MAIN caption HTTP status =', result.status);
      console.log('Lamiss POC: MAIN caption response ok =', result.ok ? 'true' : 'false');
      console.log('Lamiss POC: MAIN caption response content-type =', result.contentType);
      console.log('Lamiss POC: MAIN caption response text length =', result.text.length);

      sendResponse({
        success: true,
        ok: result.ok,
        status: result.status,
        contentType: result.contentType,
        text: result.text
      });
    } catch (error) {
      console.log('Lamiss POC: MAIN caption HTTP request completed = false');
      console.log('Lamiss POC: MAIN caption fetch error =', error instanceof Error ? error.message : String(error));
      sendResponse({
        success: false,
        error: error instanceof Error ? error.message : String(error)
      });
    }
  })();

  return true;
});

chrome.runtime.onMessage.addListener((message: unknown, _sender, _sendResponse) => {
  if (!isDiscoverTracksMessage(message)) {
    console.log('Lamiss POC: malformed DISCOVER_CAPTION_TRACKS message received');
    return false;
  }

  const tabId = message.tabId;
  const requestedLanguage = message.language.trim().toLowerCase();
  const expectedVideoId = message.videoId;
  const apiAvailable = Boolean(chrome.scripting && typeof chrome.scripting.executeScript === 'function');

  console.log('Lamiss POC: chrome.scripting available =', apiAvailable ? 'true' : 'false');

  if (!apiAvailable) {
    console.log('Lamiss POC: chrome.scripting API is unavailable');
    chrome.tabs.sendMessage(tabId, {
      type: 'CAPTION_DISCOVERY_RESULT',
      result: {
        success: false,
        error: 'chrome.scripting API is unavailable in this context'
      }
    });
    return false;
  }

  console.log('Lamiss POC: executing caption discovery in MAIN world');

  (async () => {
    try {
      const startedAt = Date.now();
      let lastResult: { success?: boolean; error?: string; tracks?: Array<{ languageCode?: string; name?: { simpleText?: string; runs?: Array<{ text?: string }> }; baseUrl?: string; kind?: string }>; diagnostics?: unknown } | undefined;

      while (Date.now() - startedAt < 5000) {
        const results = await chrome.scripting.executeScript({
          target: { tabId },
          world: 'MAIN' as chrome.scripting.ExecutionWorld,
          func: discoverCaptionTracksMainWorld,
          args: [expectedVideoId]
        });

        const result = results[0]?.result as { success?: boolean; error?: string; tracks?: Array<{ languageCode?: string; name?: { simpleText?: string; runs?: Array<{ text?: string }> }; baseUrl?: string; kind?: string }>; diagnostics?: unknown } | undefined;
        if (result?.success) {
          const trackList = Array.isArray(result.tracks) ? result.tracks : [];
          const selected = trackList.find(track => track.languageCode?.toLowerCase() === requestedLanguage);
          if (selected || trackList.length > 0) {
            lastResult = result;
            break;
          }
        }

        if (result?.success === false && result.error === 'Requested caption language is not available') {
          lastResult = result;
          break;
        }

        await new Promise(resolve => setTimeout(resolve, 250));
      }

      console.log('Lamiss POC: MAIN world execution completed');

      chrome.tabs.sendMessage(tabId, {
        type: 'CAPTION_DISCOVERY_RESULT',
        result: lastResult ?? {
          success: false,
          error: 'YouTube caption tracks are not available'
        }
      });
    } catch (error) {
      console.log('Lamiss POC: caption tracks discovered = false');
      console.log('Lamiss POC: diagnostic error =', error instanceof Error ? error.message : String(error));
      chrome.tabs.sendMessage(tabId, {
        type: 'CAPTION_DISCOVERY_RESULT',
        result: {
          success: false,
          error: error instanceof Error ? error.message : String(error)
        }
      });
    }
  })();

  return true;
});
